app:
  port: "9090"

mysql:
  host: "todo"
  port: 3307
  user: "root"
  password: "root"
  dbname: "uapply"

redis:
  host: "todo"
  port: 6379
  db: 4
  auth: "lmx15521144359"

log:
  level: "debug"
  filename: "uapply_go.log"
  max_size: 200
  max_age: 30
  max_backups: 7
  mode: "dev"